#!/bin/bash
# Установка ограниченного PATH
export PATH=$PATH:$HOME/SuperApp/scripts

# Ограничение истории команд
HISTFILE=/dev/null

# Подавление работы с job control
set +m

echo "SuperApp Терминал:"

alias help='superAppHelp'
alias ls='superAppLs'
alias cd='superAppCd'
alias mkdir='superAppMkdir'
alias rm='superAppRm'
alias rmdir='superAppRmdir'
alias ping='superAppPing'
alias hostname='superAppHostname'
alias ip='superAppIp'
alias touch='superAppTouch'
alias cp='superAppCp'
alias mv='superAppMv'
alias cat='superAppCat'
